### ISSUE TITLE
Ability to choose the webcam and microphone

### ISSUE THREAD

**Issue by zafergurel** [kixelated/quic.video#4]
### Problem
A user can have multiple devices attached. But current implementation does not allow the user to select a camera or microphone.

### Solution
Allow the user to choose the mic. and camera devices from dropdown controls which can be initialized by using `navigator.mediaDevices.enumerateDevices()` on page load.

**Comment by kixelated** [comment]
Sounds great. Let me know if you start working on this, otherwise I can take a stab.

**Comment by zafergurel** [comment]
I've started to code and will send a pull request.
